[Network]
Address = ':19132'

[Server]
Name = 'Dragonfly Server'
AuthEnabled = true
DisableJoinQuitMessages = false
MuteEmoteChat = false

[World]
SaveData = true
Folder = 'world'

[Players]
MaxCount = 0
MaximumChunkRadius = 32
SaveData = true
Folder = 'players'

[Resources]
AutoBuildPack = true
Folder = 'resources'
Required = false
